### ISSUE TITLE
Locals panel on particular frame seems to cause loop of 'Reconnecting' 

### ISSUE THREAD

**Issue by mgaudet** [Pernosco/pernosco#49] opened 2021-07-06 15:01 UTC
If you visit [this trace point](https://pernos.co/debug/F1jHj3r_0shxJLomN2ZOfA/index.html#f{m[B3qj,BRs_,t[BFM,DNg_,f{e[B3qi,AYuy_,s{afx6fOKAA,bARY,uGOoWCg,oGPPyYg___) and then open the locals panel, it appears to: load, go blank, then trigger the reconnecting prompt, then loop back to loading.

**Comment by khuey** [comment] 2021-07-06 20:20
Thanks for reporting. This was a crash caused by demangling a type name that was templated over a lambda. It's fixed now.

**Closed as completed by khuey** 2021-07-06 20:20 UTC
